### ISSUE TITLE
Monterey - E5-2680v2 x 2 (on DELL Precision T7610 )

### ISSUE THREAD

**Issue by mahmoudimus** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#10] opened 2022-08-15 18:56 UTC
Hi there -- have you successfully gotten Monterey to work with 2x E5-2680v2? I cannot even boot from USB w/ the installer. Big Sur is working wonderfully well, but I cannot get Monterey to work.

Did you install Monterey only via Installer when you had successfully installed and booted Big Sur? Maybe that's what I have to do, I just will do some backups first.

**Comment by BillDH2k** [comment] 2022-08-22 19:46
I was able to install from both ways - upgrade directly from Big Sur or fresh install from Monterey USB. Make sure you do not load "VoodooTSCSync.kext" or "CpuTscSync.kext". 

Also, if you have dual-port LAN (Z620/Z820), you should try to use "AppleIntelE1000e.kext".

**Comment by mahmoudimus** [comment] 2022-08-23 18:13
@BillDH2k did you use two processors (`2`x `E5-2680v2`) or did you have to do `cpus=1`? If I boot from the USB disk, I get  this error message: "Non-monotonic time: invoke at 0xxxxxxxxxxx, runnable...." and goes into a reboot cycle. It seems that the Monterey does not like dual-processors.

**Comment by BillDH2k** [comment] 2022-08-24 14:19
I have 2x 2680v2 on a Z820, running Monterey without any issue. No "cpus=1" flag is required.  What other hardware add-on you have? Post you Config.plist here (without ss#).

**Comment by mahmoudimus** [comment] 2022-08-24 15:51
Hi @BillDH2k thanks for the response. Here's my entire setup, which works very well for Big Sur: https://github.com/mahmoudimus/oc-dell-precision-t7610-workstation

I know it's not a Z420, Z620, or Z820, but those HP models are actually very similar to the Dell T7610 workstations (including the CPU versions, etc). Same SAS controller, etc. So I just needed to see that it was possible to have Monterey work at a 2x 2680v2 processor (which you said you have and apparently works fine?). 

I haven't tried upgrading Monterey with the installer from Big Sur. I am terrified if I do so though that my entire hackintosh setup won't work :( So that's why I'm a bit hesitant to try the installer without at least verifying that I can boot my system via Monterey first 😛

**Comment by BillDH2k** [comment] 2022-08-24 21:59
Checked your config.plist.  You still have "VoodooTSCSync.kext" loaded (under Root->Kernel->Add) which is known to cause kernel panic under Monterey. You have to to disable it (Set "Enabled" to "False"). 

You could make a duplicate of your current OS partition to a separate drive and then try out your install on the duplicated drive (so you don't touch your original OS drive, by removing it during your experiment). You can use "disk utility" to make a duplicate of your current OS partition.

**Comment by mahmoudimus** [comment] 2022-08-25 13:25
Thanks for that idea. Let me try. 

> Checked your config.plist. You still have "VoodooTSCSync.kext" loaded (under Root->Kernel->Add) which is known to cause kernel panic under Monterey. You have to to disable it (Set "Enabled" to "False").

I did disable that to false, I'll double check and try again. Thank you for your help on this one. I'll let you know the results of this soon.

**Comment by mahmoudimus** [comment] 2022-10-02 01:02
Just wanted to follow up with this. It still fails to boot up. Big Sur is working perfectly though.

**Comment by BillDH2k** [comment] 2022-10-02 15:47
Other Dell systems, like T5810/7810, have appeared to be exactly the same issues under Monterey.

**Comment by mahmoudimus** [comment] 2022-10-02 15:49
It's not clear how to even debug this problem. I'm happy to dive in to the code and figure it out, but it's not clear to me how to debug or create output etc.

**Comment by BillDH2k** [comment] 2022-10-19 01:43
I did some googling for "kernel panic due to Non-monotonic time". It appears that the root cause to be with Dell's BIOS which fail to initiate all cores with TSC synch. Unlike Big Sur, Monterey will branch out early before user added CpuTscSync.kext to kick in, thus causing panic. HP BIOS, however, will perform the TSC synch properly, thus no need for CpuTscSync.kext.

**Comment by luhua98989898** [comment] 2022-11-02 03:57
> Hi there -- have you successfully gotten Monterey to work with 2x E5-2680v2? I cannot even boot from USB w/ the installer. Big Sur is working wonderfully well, but I cannot get Monterey to work.
> 
> Did you install Monterey only via Installer when you had successfully installed and booted Big Sur? Maybe that's what I have to do, I just will do some backups first.



> Hi there -- have you successfully gotten Monterey to work with 2x E5-2680v2? I cannot even boot from USB w/ the installer. Big Sur is working wonderfully well, but I cannot get Monterey to work.
> 
> Did you install Monterey only via Installer when you had successfully installed and booted Big Sur? Maybe that's what I have to do, I just will do some backups first.

hi ,my PC is DELL T5600  and the cpu is dual 2680 v5,and now can't install the MAC OS , can you tell me how install it now?

**Comment by luhua98989898** [comment] 2022-11-02 03:58
> I did some googling for "kernel panic due to Non-monotonic time". It appears that the root cause to be with Dell's BIOS which fail to initiate all cores with TSC synch. Unlike Big Sur, Monterey will branch out early before user added CpuTscSync.kext to kick in, thus causing panic. HP BIOS, however, will perform the TSC synch properly, thus no need for CpuTscSync.kext.

hi ,my PC is DELL T5600 and the cpu is dual 2680 v5,and now can't install the MAC OS , can you tell me how install it now?

**Comment by BillDH2k** [comment] 2022-11-08 16:35
@luhua98989898 
Have you tried this [guide (DellT5600Hackintosh)](https://github.com/kevinisaacperez/DellT5600Hackintosh)? It was written for Catalina (try it first), but with some minor changes, you should be able to use it for Big Sur. You need to create your own SSDT-PM.aml for your E5-2680 V1 CPU (not V5). That guide was using E5-2630 V1. But you should be able to boot without using it (same as not using SSDT-CPUPM.aml as described in my guide). 

For further help, please visit insanelymac.com forum.

**Closed as completed** 2022-12-11 23:29 UTC

**Comment by mahmoudimus** [comment] 2022-12-11 23:45
@BillDH2k i think you have solved this with:

> `ResetTSCAdjust.efi` tool by denskop (https://github.com/denskop/VoodooTSCSync/issues/1#issuecomment-629837192). This little tool allowed CPU TSC sync to be performed before macOS luanch (DELL BIOS failed to do this). Without this, Monterey/Ventura booting would encounter kernel panic due to "non-monotonic time" error.

Will check it and let you know

**Comment by BillDH2k** [comment] 2022-12-12 18:04
No. That tool only works under X99 platform and it could not run under X79 based boards with older UEFI BIOS. Follow the thread [here](https://www.insanelymac.com/forum/topic/341600-success-huananzhi-x79-zd3-xeon-e5-2689-mojave-10146-big-sur-1123-monterey-1201/?do=findComment&comment=2796692).

**Comment by mahmoudimus** [comment] 2022-12-20 03:24
@BillDH2k fyi, https://github.com/acidanthera/bugtracker/issues/1864#issuecomment-1358788096 I think there's hope.
